# MidBootcamp Project:

### Import libraries:

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import re

### Load data:

In [64]:
df = pd.read_csv("../Data/WorldCupMatches.csv",parse_dates=[1]) 

df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

### Data exploring:

We'll start by checking the types of columns there are and the shape of the dataframe:

In [3]:
df.info()

print('The dataframes shape is: ', df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    datetime64[ns]
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: datetime64[ns](1), float64(8), object(11)
memory usage: 714.5+ KB
The dataframes shape is:  (4572, 20)

In [4]:
df['Year'].unique()

array([1930., 1934., 1938., 1950., 1954., 1958., 1962., 1966., 1970.,
       1974., 1978., 1982., 1986., 1990., 1994., 1998., 2002., 2006.,
       2010., 2014.,   nan])

We can see the dataframe goes from the year 1930 to 2014.

In [5]:
df['Home Team Name'].unique()

array(['France', 'USA', 'Yugoslavia', 'Romania', 'Argentina', 'Chile',
       'Uruguay', 'Brazil', 'Paraguay', 'Austria', 'Hungary',
       'Switzerland', 'Sweden', 'Germany', 'Spain', 'Italy',
       'Czechoslovakia', 'Cuba', 'England', 'Germany FR', 'Turkey',
       'Soviet Union', 'Northern Ireland', 'Mexico', 'Wales', 'Portugal',
       'Korea DPR', 'Peru', 'Belgium', 'Bulgaria', 'German DR', 'Zaire',
       'Poland', 'Australia', 'Scotland', 'Netherlands', 'Haiti',
       'Tunisia', 'Algeria', 'Honduras', 'Canada', 'Morocco',
       'Korea Republic', 'Iraq', 'Denmark', 'rn">United Arab Emirates',
       'Costa Rica', 'Cameroon', 'rn">Republic of Ireland', 'Colombia',
       'Norway', 'Nigeria', 'Saudi Arabia', 'Bolivia', 'Russia', 'Greece',
       'Jamaica', 'South Africa', 'Japan', 'Croatia', 'China PR',
       'Senegal', 'Slovenia', 'Ecuador', 'rn">Trinidad and Tobago',
       'rn">Serbia and Montenegro', 'Angola', 'Czech Republic', 'Togo',
       'Iran', "C�te d'Ivoire", 'Ghana', 'Ukraine', 'Serbia',
       'New Zealand', 'Slovakia', 'IR Iran', 'rn">Bosnia and Herzegovina',
       nan], dtype=object)

In [6]:
df['Away Team Name'].unique()

array(['Mexico', 'Belgium', 'Brazil', 'Peru', 'France', 'Bolivia',
       'Paraguay', 'Romania', 'Chile', 'USA', 'Yugoslavia', 'Argentina',
       'Egypt', 'Netherlands', 'Switzerland', 'Sweden', 'Spain',
       'Hungary', 'Austria', 'Germany', 'Czechoslovakia',
       'Dutch East Indies', 'Norway', 'Poland', 'Cuba', 'Italy',
       'England', 'Scotland', 'Turkey', 'Korea Republic', 'Germany FR',
       'Uruguay', 'Wales', 'Northern Ireland', 'Soviet Union', 'Colombia',
       'Bulgaria', 'Korea DPR', 'Portugal', 'Israel', 'Morocco',
       'El Salvador', 'Australia', 'Haiti', 'German DR', 'Zaire',
       'IR Iran', 'Tunisia', 'Iran', 'Cameroon', 'New Zealand', 'Algeria',
       'Honduras', 'Kuwait', 'Iraq', 'Denmark', 'Canada',
       'rn">Republic of Ireland', 'rn">United Arab Emirates',
       'Costa Rica', 'Saudi Arabia', 'Russia', 'Greece', 'Nigeria',
       'South Africa', 'Japan', 'Croatia', 'Jamaica', 'Senegal',
       'Slovenia', 'Ecuador', 'China PR', "C�te d'Ivoire",
       'Czech Republic', 'Ghana', 'Togo', 'Ukraine',
       'rn">Trinidad and Tobago', 'rn">Serbia and Montenegro', 'Angola',
       'Slovakia', 'Serbia', 'rn">Bosnia and Herzegovina', nan],
      dtype=object)

Will need to fix the names of a few countries: C�te d'Ivoire, rn">Trinidad and Tobago, rn">Serbia and Montenegro, rn">Bosnia and Herzegovina.

### Checking for NaN values:

In [65]:
df.iloc[60:855]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
60,1950.0,1950-06-29 15:00:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,2.0,0.0,Chile,,19790.0,2.0,0.0,MALCHER Alberto (BRA),MARINO Esteban (URU),ALVAREZ Alfredo (BOL),208.0,1193.0,ESP,CHI
61,1950.0,1950-06-29 15:30:00,Group 3,Durival de Brito,Curitiba,Sweden,2.0,2.0,Paraguay,,7903.0,2.0,1.0,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208.0,1228.0,SWE,PAR
62,1950.0,1950-06-29 15:00:00,Group 2,Independencia,Belo Horizonte,USA,1.0,0.0,England,,10151.0,1.0,0.0,DATTILO Generoso (ITA),DE LA SALLE Charles (FRA),GALEATI Giovanni (ITA),208.0,1202.0,USA,ENG
63,1950.0,1950-07-01 15:00:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,2.0,0.0,Yugoslavia,,142429.0,1.0,0.0,GRIFFITHS Benjamin (WAL),BERANEK Alois (AUT),DA COSTA VIEIRA Jose (POR),208.0,1191.0,BRA,YUG
64,1950.0,1950-07-02 15:00:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,1.0,0.0,England,,74462.0,0.0,0.0,GALEATI Giovanni (ITA),LUTZ Jean (SUI),DATTILO Generoso (ITA),208.0,1199.0,ESP,ENG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,2014.0,2014-07-12 17:00:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,68034.0,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED
851,2014.0,2014-07-13 16:00:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time,74738.0,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG
852,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
853,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
854,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The data goes from the World Cup in Uruguay in 1930 to the 2014 World Cup celebrated in Brasil. Which means we have 3720 blank values in the dataframe.

In [8]:
na = print(df.isna().sum())

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

### Dropping the NaN values:

In [9]:
df = df.dropna()

df.isna().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

### Standardize column names:

In [10]:
cols = []
for x in df.columns:
    cols.append(x.lower().replace(' ','_'))
    
df.columns = cols

df.columns

Index(['year', 'datetime', 'stage', 'stadium', 'city', 'home_team_name',
       'home_team_goals', 'away_team_goals', 'away_team_name',
       'win_conditions', 'attendance', 'half-time_home_goals',
       'half-time_away_goals', 'referee', 'assistant_1', 'assistant_2',
       'roundid', 'matchid', 'home_team_initials', 'away_team_initials'],
      dtype='object')

### Transforming columns into integers:

The numerical columns: 'year', 'home_team_goals', 'attendance', 'away_team_goals', 'half-time_home_goals' and 'half-time_away_goals' are all floats (continuous) values. However, on the dataframe we are seeing discrete values since none of them can be measured by splitting. So we'll be transforming values in these columns into integers.

In [11]:
df['year'] = df['year'].apply(np.int64)
df['home_team_goals'] = df['home_team_goals'].apply(np.int64)
df['away_team_goals'] = df['away_team_goals'].apply(np.int64)
df['half-time_home_goals'] = df['half-time_home_goals'].apply(np.int64)
df['half-time_away_goals'] = df['half-time_away_goals'].apply(np.int64)
df['attendance'] = df['attendance'].apply(np.int64)

df.dtypes

year                             int64
datetime                datetime64[ns]
stage                           object
stadium                         object
city                            object
home_team_name                  object
home_team_goals                  int64
away_team_goals                  int64
away_team_name                  object
win_conditions                  object
attendance                       int64
half-time_home_goals             int64
half-time_away_goals             int64
referee                         object
assistant_1                     object
assistant_2                     object
roundid                        float64
matchid                        float64
home_team_initials              object
away_team_initials              object
dtype: object

### Changing datetime column to display day/month/year of the game:

In [12]:
df['datetime'] = df['datetime'].dt.strftime('%d/%m/%Y')

In [13]:
df = df.rename(columns={'datetime': 'date'})

In [14]:
df.head()

,year,date,stage,stadium,city,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,attendance,half-time_home_goals,half-time_away_goals,referee,assistant_1,assistant_2,roundid,matchid,home_team_initials,away_team_initials
0,1930,13/07/1930,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930,13/07/1930,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930,14/07/1930,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930,14/07/1930,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930,15/07/1930,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

### Stage:

Checking all the different values inside stage:

In [15]:
df['stage'].unique()

array(['Group 1', 'Group 4', 'Group 2', 'Group 3', 'Semi-finals', 'Final',
       'Preliminary round', 'Quarter-finals', 'Match for third place',
       'First round', 'Group 6', 'Group B', 'Group A', 'Group 5',
       'Group C', 'Group D', 'Group F', 'Group E', 'Round of 16',
       'Group H', 'Group G', 'Third place', 'Play-off for third place'],
      dtype=object)

Switching the Group Stages to the same ABCD format.

In [16]:
df['stage'] = df['stage'].replace({'Group 1': 'Group A', 'Group 2':'Group B', 
                                   'Group 3': 'Group C', 'Group 4': 'Group D'})

In [17]:
df['stage'].value_counts()

Group A                     122
Group B                     119
Group C                     104
Group D                     103
Round of 16                  70
Quarter-finals               66
Group F                      48
Group E                      48
Semi-finals                  36
Group G                      30
Group H                      30
Final                        20
Match for third place        15
Group 6                      12
First round                   9
Preliminary round             8
Group 5                       6
Third place                   2
Play-off for third place      2
Name: stage, dtype: int64

### Stadium:

Checking the all the stadium names:

In [18]:
df['stadium'].unique()

array(['Pocitos', 'Parque Central', 'Estadio Centenario',
       'Stadio Benito Mussolini', 'Giorgio Ascarelli', 'San Siro',
       'Littorale', 'Giovanni Berta', 'Luigi Ferraris', 'Nazionale PNF',
       'Littorio', 'Parc des Princes', 'Velodrome Municipale',
       'Stade Olympique', 'Stade Municipal', 'Stade V�lodrome',
       'Stade de la Meinau', 'Cavee Verte', 'Stade du Parc Lescure',
       'Victor Boucquey', 'Fort Carree',
       'Maracan� - Est�dio Jornalista M�rio Filho', 'Durival de Brito',
       'Pacaembu', 'Independencia', 'Eucaliptos', 'Ilha do Retiro',
       'Wankdorf Stadium', 'Hardturm', 'Charmilles', 'La Pontaise',
       'St. Jakob', 'Comunale di Cornaredo', 'Rasunda Stadium',
       'Nya Ullevi', 'Malmo Stadion', 'Jarnvallen', 'Idrottsparken',
       'Arosvallen', 'Rimnersvallen', 'Orjans Vall', 'Ryavallen',
       'Olympia Stadium', 'Tunavallen', 'Eyravallen', 'Carlos Dittborn',
       'Estadio Sausalito', 'Estadio El Teniente-Codelco', 'Nacional',
       'Wembley Stadium', 'Hillsborough', 'Goodison Park',
       'Ayresome Park', 'Old Trafford Stadium', 'Villa Park',
       'Roker Park Ground', 'White City', 'Estadio Azteca', 'Cuauhtemoc',
       'Nou Camp - Estadio Le�n', 'Jalisco', 'Luis Dosal', 'Waldstadion',
       'Olympiastadion', 'Volksparkstadion', 'Westfalenstadion',
       'Niedersachsenstadion', 'Rheinstadion', 'Neckarstadion',
       'Parkstadion',
       'El Monumental - Estadio Monumental Antonio Vespuci',
       'Estadio Jos� Mar�a Minella',
       'Arroyito - Estadio Dr. Lisandro de la Torre', 'Jose Amalfitani',
       'Estadio Ol�mpico Chateau Carreras', 'San Martin', 'Camp Nou',
       'Estadio Municipal de Bala�dos', 'Ramon Sanchez Pizjuan', 'Riazor',
       'Nuevo Estadio', 'La Rosaleda', 'El Molinon', 'San Mames',
       'Luis Casanova', 'Carlos Tartiere', 'Jose Zorrilla', 'La Romareda',
       'Jose Rico Perez', 'Benito Villamarin', 'Vicente Calderon',
       'Sarria', 'Santiago Bernabeu', 'Estadio Irapuato',
       'Estadio Ol�mpico Universitario', 'Estadio Universitario',
       'Tres de Marzo', 'Tecnologico', 'Bombonera - Estadio Nemesio Diez',
       'Neza', 'Estadio Corregidora', 'Giuseppe Meazza',
       'Stadio San Nicola', 'Renato Dall Ara', 'Stadio Olimpico',
       'Comunale', 'Stadio delle Alpi', 'Sant Elia',
       'Marc Antonio Bentegodi', 'Della Favorita', 'Dacia Arena',
       'San Paolo', 'Friuli', 'Cotton Bowl', 'Soldier Field',
       'Pontiac Silverdome', 'Giants Stadium', 'Rose Bowl', 'Citrus Bowl',
       'RFK Stadium', 'Stanford Stadium', 'Foxboro Stadium',
       'Stade de France', 'La Mosson', 'Stade Felix Bollaert',
       'La Beaujoire', 'Stade de Gerland', 'Stade Geoffroy Guichard',
       'Seoul World Cup Stadium', 'Munsu Football Stadium',
       'Niigata Stadium Big Swan', 'Sapporo Dome', 'Kashima Stadium',
       'Busan Asiad Main Stadium', 'Saitama Stadium 2002',
       'Gwangju World Cup Stadium', 'Kobe Wing Stadium',
       'Suwon World Cup Stadium', 'Daegu World Cup Stadium',
       'Jeonju World Cup Stadium', 'Jeju World Cup Stadium',
       'Incheon Football Stadium', 'International Stadium Yokohama',
       'Miyagi Stadium', 'Oita Stadium Big Eye', 'Shizuoka Stadium Ecopa',
       'Osaka Nagai Stadium', 'Daejeon World Cup Stadium',
       'FIFA World Cup Stadium, Munich',
       'FIFA World Cup Stadium, Gelsenkirchen',
       'FIFA World Cup Stadium, Frankfurt',
       'FIFA World Cup Stadium, Dortmund',
       'FIFA World Cup Stadium, Hamburg', 'Zentralstadion',
       'Franken-Stadion', 'FIFA World Cup Stadium, Cologne',
       'Fritz-Walter-Stadion', 'FIFA World Cup Stadium, Hanover',
       'Gottlieb-Daimler-Stadion', 'Soccer City Stadium',
       'Cape Town Stadium', 'Port Elizabeth Stadium',
       'Ellis Park Stadium', 'Royal Bafokeng Sports Palace',
       'Peter Mokaba Stadium', 'Loftus Versfeld Stadium',
       'Durban Stadium', 'Free State Stadium', 'Mbombela Stadium',
       'Arena de Sao Paulo', 'Estadio das Dunas', 'Arena Fonte Nova',
       'Arena Pantanal', 'Estadio Mineirao', 'Estadio Castelao',
       'Arena Amazonia', 'Arena Pernambuco', 'Estadio Nacional',
       'Estadio Beira-Rio', 'Estadio do Maracana', 'Arena da Baixada'],
      dtype=object)

### Fixing stadium names:

We'll be replacing the name with � for the actual name.

In [19]:
df['stadium'] = df['stadium'].replace(
    {'Stade V�lodrome': 'Stade Vélodrome', 
     'Maracan� - Est�dio Jornalista M�rio Filho': 'Maracanã - Estádio Jornalista Mário Filho',
    'Nou Camp - Estadio Le�n': 'Estadio León', 'Estadio Jos� Mar�a Minella': 'Estadio José María Minella',
    'Estadio Ol�mpico Chateau Carreras': 'Estadio Olímpico Chateau Carreras',
    'Estadio Municipal de Bala�dos': 'Estadio Municipal de Balaídos', 
     'Estadio Ol�mpico Universitario': 'Estadio Olímpico Universitario'})

In [20]:
df['stadium'].unique()

array(['Pocitos', 'Parque Central', 'Estadio Centenario',
       'Stadio Benito Mussolini', 'Giorgio Ascarelli', 'San Siro',
       'Littorale', 'Giovanni Berta', 'Luigi Ferraris', 'Nazionale PNF',
       'Littorio', 'Parc des Princes', 'Velodrome Municipale',
       'Stade Olympique', 'Stade Municipal', 'Stade Vélodrome',
       'Stade de la Meinau', 'Cavee Verte', 'Stade du Parc Lescure',
       'Victor Boucquey', 'Fort Carree',
       'Maracanã - Estádio Jornalista Mário Filho', 'Durival de Brito',
       'Pacaembu', 'Independencia', 'Eucaliptos', 'Ilha do Retiro',
       'Wankdorf Stadium', 'Hardturm', 'Charmilles', 'La Pontaise',
       'St. Jakob', 'Comunale di Cornaredo', 'Rasunda Stadium',
       'Nya Ullevi', 'Malmo Stadion', 'Jarnvallen', 'Idrottsparken',
       'Arosvallen', 'Rimnersvallen', 'Orjans Vall', 'Ryavallen',
       'Olympia Stadium', 'Tunavallen', 'Eyravallen', 'Carlos Dittborn',
       'Estadio Sausalito', 'Estadio El Teniente-Codelco', 'Nacional',
       'Wembley Stadium', 'Hillsborough', 'Goodison Park',
       'Ayresome Park', 'Old Trafford Stadium', 'Villa Park',
       'Roker Park Ground', 'White City', 'Estadio Azteca', 'Cuauhtemoc',
       'Estadio León', 'Jalisco', 'Luis Dosal', 'Waldstadion',
       'Olympiastadion', 'Volksparkstadion', 'Westfalenstadion',
       'Niedersachsenstadion', 'Rheinstadion', 'Neckarstadion',
       'Parkstadion',
       'El Monumental - Estadio Monumental Antonio Vespuci',
       'Estadio José María Minella',
       'Arroyito - Estadio Dr. Lisandro de la Torre', 'Jose Amalfitani',
       'Estadio Olímpico Chateau Carreras', 'San Martin', 'Camp Nou',
       'Estadio Municipal de Balaídos', 'Ramon Sanchez Pizjuan', 'Riazor',
       'Nuevo Estadio', 'La Rosaleda', 'El Molinon', 'San Mames',
       'Luis Casanova', 'Carlos Tartiere', 'Jose Zorrilla', 'La Romareda',
       'Jose Rico Perez', 'Benito Villamarin', 'Vicente Calderon',
       'Sarria', 'Santiago Bernabeu', 'Estadio Irapuato',
       'Estadio Olímpico Universitario', 'Estadio Universitario',
       'Tres de Marzo', 'Tecnologico', 'Bombonera - Estadio Nemesio Diez',
       'Neza', 'Estadio Corregidora', 'Giuseppe Meazza',
       'Stadio San Nicola', 'Renato Dall Ara', 'Stadio Olimpico',
       'Comunale', 'Stadio delle Alpi', 'Sant Elia',
       'Marc Antonio Bentegodi', 'Della Favorita', 'Dacia Arena',
       'San Paolo', 'Friuli', 'Cotton Bowl', 'Soldier Field',
       'Pontiac Silverdome', 'Giants Stadium', 'Rose Bowl', 'Citrus Bowl',
       'RFK Stadium', 'Stanford Stadium', 'Foxboro Stadium',
       'Stade de France', 'La Mosson', 'Stade Felix Bollaert',
       'La Beaujoire', 'Stade de Gerland', 'Stade Geoffroy Guichard',
       'Seoul World Cup Stadium', 'Munsu Football Stadium',
       'Niigata Stadium Big Swan', 'Sapporo Dome', 'Kashima Stadium',
       'Busan Asiad Main Stadium', 'Saitama Stadium 2002',
       'Gwangju World Cup Stadium', 'Kobe Wing Stadium',
       'Suwon World Cup Stadium', 'Daegu World Cup Stadium',
       'Jeonju World Cup Stadium', 'Jeju World Cup Stadium',
       'Incheon Football Stadium', 'International Stadium Yokohama',
       'Miyagi Stadium', 'Oita Stadium Big Eye', 'Shizuoka Stadium Ecopa',
       'Osaka Nagai Stadium', 'Daejeon World Cup Stadium',
       'FIFA World Cup Stadium, Munich',
       'FIFA World Cup Stadium, Gelsenkirchen',
       'FIFA World Cup Stadium, Frankfurt',
       'FIFA World Cup Stadium, Dortmund',
       'FIFA World Cup Stadium, Hamburg', 'Zentralstadion',
       'Franken-Stadion', 'FIFA World Cup Stadium, Cologne',
       'Fritz-Walter-Stadion', 'FIFA World Cup Stadium, Hanover',
       'Gottlieb-Daimler-Stadion', 'Soccer City Stadium',
       'Cape Town Stadium', 'Port Elizabeth Stadium',
       'Ellis Park Stadium', 'Royal Bafokeng Sports Palace',
       'Peter Mokaba Stadium', 'Loftus Versfeld Stadium',
       'Durban Stadium', 'Free State Stadium', 'Mbombela Stadium',
       'Arena de Sao Paulo', 'Estadio das Dunas', 'Arena Fonte Nova',
       'Arena Pantanal', 'Estadio Mineirao', 'Estadio Castelao',
       'Arena Amazonia', 'Arena Pernambuco', 'Estadio Nacional',
       'Estadio Beira-Rio', 'Estadio do Maracana', 'Arena da Baixada'],
      dtype=object)

### City:

Now we'll do the same for the 'city' column:

In [21]:
df['city'].unique()

array(['Montevideo ', 'Turin ', 'Naples ', 'Milan ', 'Bologna ',
       'Florence ', 'Genoa ', 'Rome ', 'Trieste ', 'Paris ', 'Reims ',
       'Colombes ', 'Toulouse ', 'Marseilles ', 'Strasbourg ',
       'Le Havre ', 'Bordeaux ', 'Lille ', 'Antibes ', 'Rio De Janeiro ',
       'Curitiba ', 'Sao Paulo ', 'Belo Horizonte ', 'Porto Alegre ',
       'Recife ', 'Berne ', 'Zurich ', 'Geneva ', 'Lausanne ', 'Basel ',
       'Lugano ', 'Solna ', 'Gothenburg ', 'Malm� ', 'Sandviken ',
       'Norrk�Ping ', 'Vasteras ', 'Udevalla ', 'Halmstad ', 'Boras ',
       'Helsingborg ', 'Eskilstuna ', 'Orebro ', 'Arica ',
       'Vina Del Mar ', 'Rancagua ', 'Santiago De Chile ', 'London ',
       'Sheffield ', 'Liverpool ', 'Middlesbrough ', 'Manchester ',
       'Birmingham ', 'Sunderland ', 'Mexico City ', 'Puebla ', 'Leon ',
       'Guadalajara ', 'Toluca ', 'Frankfurt/Main ', 'Berlin West ',
       'Hamburg ', 'Dortmund ', 'Hanover ', 'D�Sseldorf ', 'Munich ',
       'Stuttgart ', 'Gelsenkirchen ', 'Buenos Aires ', 'Mar Del Plata ',
       'Rosario ', 'Cordoba ', 'Mendoza ', 'Barcelona ', 'Vigo ',
       'Seville ', 'La Coru�A ', 'Elche ', 'Malaga ', 'Gijon ', 'Bilbao ',
       'Valencia ', 'Oviedo ', 'Valladolid ', 'Zaragoza ', 'Alicante ',
       'Madrid ', 'Irapuato ', 'Monterrey ', 'Nezahualcoyotl ',
       'Queretaro ', 'Bari ', 'Cagliari ', 'Verona ', 'Palermo ',
       'Udine ', 'Dallas ', 'Chicago ', 'Detroit ',
       'New York/New Jersey ', 'Los Angeles ', 'Orlando ',
       'Washington Dc ', 'San Francisco ', 'Boston ', 'Saint-Denis ',
       'Montpellier ', 'Lens ', 'Nantes ', 'Lyon ', 'Saint-Etienne ',
       'Seoul ', 'Ulsan ', 'Niigata ', 'Sapporo ', 'Ibaraki ', 'Busan ',
       'Saitama ', 'Gwangju ', 'Kobe ', 'Suwon ', 'Daegu ', 'Jeonju ',
       'Jeju ', 'Incheon ', 'Yokohama ', 'Rifu ', 'Oita ', 'Shizuoka ',
       'Osaka ', 'Daejeon ', 'Leipzig ', 'Nuremberg ', 'Cologne ',
       'Kaiserslautern ', 'Berlin ', 'Johannesburg ', 'Cape Town ',
       'Nelson Mandela Bay/Port Elizabeth ', 'Phokeng ', 'Polokwane ',
       'Tshwane/Pretoria ', 'Durban ', 'Mangaung/Bloemfontein ',
       'Nelspruit ', 'Natal ', 'Salvador ', 'Cuiaba ', 'Fortaleza ',
       'Manaus ', 'Brasilia '], dtype=object)

### Fixing City names:

All the values have an empty space at the end of the name, so we'll take it out with a right split before fixing the column names.

In [22]:
df['city'] = df['city'].map(lambda x: x.rstrip(' '))

In [23]:
df['city'] = df['city'].replace(
    {'Malm�': 'Malmö', 'Norrk�Ping': 'NorrköPing', 'D�Sseldorf': 'Düsseldorf', 'La Coru�A': 'La Coruña'})

In [24]:
df['city'].unique()

array(['Montevideo', 'Turin', 'Naples', 'Milan', 'Bologna', 'Florence',
       'Genoa', 'Rome', 'Trieste', 'Paris', 'Reims', 'Colombes',
       'Toulouse', 'Marseilles', 'Strasbourg', 'Le Havre', 'Bordeaux',
       'Lille', 'Antibes', 'Rio De Janeiro', 'Curitiba', 'Sao Paulo',
       'Belo Horizonte', 'Porto Alegre', 'Recife', 'Berne', 'Zurich',
       'Geneva', 'Lausanne', 'Basel', 'Lugano', 'Solna', 'Gothenburg',
       'Malmö', 'Sandviken', 'NorrköPing', 'Vasteras', 'Udevalla',
       'Halmstad', 'Boras', 'Helsingborg', 'Eskilstuna', 'Orebro',
       'Arica', 'Vina Del Mar', 'Rancagua', 'Santiago De Chile', 'London',
       'Sheffield', 'Liverpool', 'Middlesbrough', 'Manchester',
       'Birmingham', 'Sunderland', 'Mexico City', 'Puebla', 'Leon',
       'Guadalajara', 'Toluca', 'Frankfurt/Main', 'Berlin West',
       'Hamburg', 'Dortmund', 'Hanover', 'Düsseldorf', 'Munich',
       'Stuttgart', 'Gelsenkirchen', 'Buenos Aires', 'Mar Del Plata',
       'Rosario', 'Cordoba', 'Mendoza', 'Barcelona', 'Vigo', 'Seville',
       'La Coruña', 'Elche', 'Malaga', 'Gijon', 'Bilbao', 'Valencia',
       'Oviedo', 'Valladolid', 'Zaragoza', 'Alicante', 'Madrid',
       'Irapuato', 'Monterrey', 'Nezahualcoyotl', 'Queretaro', 'Bari',
       'Cagliari', 'Verona', 'Palermo', 'Udine', 'Dallas', 'Chicago',
       'Detroit', 'New York/New Jersey', 'Los Angeles', 'Orlando',
       'Washington Dc', 'San Francisco', 'Boston', 'Saint-Denis',
       'Montpellier', 'Lens', 'Nantes', 'Lyon', 'Saint-Etienne', 'Seoul',
       'Ulsan', 'Niigata', 'Sapporo', 'Ibaraki', 'Busan', 'Saitama',
       'Gwangju', 'Kobe', 'Suwon', 'Daegu', 'Jeonju', 'Jeju', 'Incheon',
       'Yokohama', 'Rifu', 'Oita', 'Shizuoka', 'Osaka', 'Daejeon',
       'Leipzig', 'Nuremberg', 'Cologne', 'Kaiserslautern', 'Berlin',
       'Johannesburg', 'Cape Town', 'Nelson Mandela Bay/Port Elizabeth',
       'Phokeng', 'Polokwane', 'Tshwane/Pretoria', 'Durban',
       'Mangaung/Bloemfontein', 'Nelspruit', 'Natal', 'Salvador',
       'Cuiaba', 'Fortaleza', 'Manaus', 'Brasilia'], dtype=object)

### Referee and assistants:

Instead of using the whole name of the referees and their assistants, we'll be using the nationality which is conviniently placed inside parenthesis.

In [25]:
df['referee'].unique()

array(['LOMBARDI Domingo (URU)', 'MACIAS Jose (ARG)',
       'TEJADA Anibal (URU)', 'WARNKEN Alberto (CHI)',
       'REGO Gilberto (BRA)', 'CRISTOPHE Henry (BEL)',
       'MATEUCCI Francisco (URU)', 'LANGENUS Jean (BEL)',
       'SAUCEDO Ulises (BOL)', 'BALWAY Thomas (FRA)',
       'VALLARINO Ricardo (URU)', 'VAN MOORSEL Johannes (NED)',
       'BARLASSINA Rinaldo (ITA)', 'EKLIND Ivan (SWE)',
       'BRAUN Eugen (AUT)', 'MATTEA Francesco (ITA)',
       'BIRLEM Alfred (GER)', 'MERCET Rene (SUI)', 'BERANEK Alois (AUT)',
       'BAERT Louis (BEL)', 'CARRARO Albino (ITA)', 'CONRIE Roger (FRA)',
       'WUETHRICH Hans (SUI)', 'SCARPI Giuseppe (ITA)',
       'LECLERCQ Lucien (FRA)', 'VON HERTZKA Pal (HUN)',
       'KRIST Gustav (TCH)', 'CAPDEVILLE Georges (FRA)',
       'READER George (ENG)', 'VAN DER MEER Karel (NED)',
       'VIANA Mario (BRA)', 'LUTZ Jean (SUI)', 'GALEATI Giovanni (ITA)',
       'AZON ROMA Ramon (ESP)', 'LEAFE Reginald (ENG)',
       'MALCHER Alberto (BRA)', 'MITCHELL Robert (SCO)',
       'DATTILO Generoso (ITA)', 'GRIFFITHS Benjamin (WAL)',
       'ELLIS Arthur (ENG)', 'GARDELLI Mario (BRA)',
       'FRANKEN Laurent (BEL)', 'WYSSLING Paul (SUI)',
       'DA COSTA VIEIRA Jose (POR)', 'VINCENTI Raymond (FRA)',
       'SCHMETZER Emil (FRG)', 'ORLANDINI Vincenzo (ITA)',
       'STEFANOVIC Vasa (YUG)', 'ASENSI Manuel (ESP)',
       'FAULTLESS Charlie (SCO)', 'LING William (ENG)',
       'MARINO Esteban (URU)', 'ZSOLT Istvan (HUN)', 'STEINER Carl (AUT)',
       'LATYCHEV Nikolaj (URS)', 'CODESAL Jose Maria (URU)',
       'GARDEAZABAL Juan (ESP)', 'GUIGUE Maurice (FRA)',
       'SEIPELT Fritz (AUT)', 'DUSCH Albert (GER)', 'LEMESIC Leo (YUG)',
       'JORGENSEN Carl Frederik (DEN)', 'AHLNER Sten (SWE)',
       'MOWAT Jack (SCO)', 'VAN NUFFEL Lucien (BEL)',
       'FERNANDES CAMPOS Joaquim (POR)', 'ERIKSSON Arne (FIN)',
       'MACKO Martin (TCH)', 'BROZZI Juan (ARG)', 'BRONKHORST Jan (NED)',
       'DOROGI Andor (HUN)', 'DIENST Gottfried (SUI)', 'ASTON Ken (ENG)',
       'HORN Leo (NED)', 'DAVIDSON Bob (SCO)', 'GALBA Karol (TCH)',
       'SCHWINTE Pierre (FRA)', 'ETZEL FILHO Joao (BRA)',
       'TESANIC Branko (YUG)', 'JONNI Cesare (ITA)',
       'BUSTAMANTE Sergio (CHI)', 'YAMASAKI MALDONADO Arturo (MEX)',
       'ROBLES Carlos (CHI)', 'BLAVIER Arthur (BEL)',
       'PHILLIPS Hugh (SCO)', 'TSCHENSCHER Kurt (GER)',
       'ASHKENAZI Menachem (ISR)', 'CALLAGHAN Leo (WAL)',
       'RUMENTCHEV Dimitar (BUL)', 'BAKHRAMOV Tofik (URS)',
       'DAGNALL Kenneth (ENG)', 'KANDIL Aly Hussein (EGY)',
       'ZECEVIC Konstantin (YUG)', 'KREITLEIN Rudolf (GER)',
       'LO BELLO Concetto (ITA)', 'LOEOEW Bertil (SWE)',
       'McCABE George (ENG)', 'GOICOECHEA Roberto (ARG)',
       'MARQUES Armando (BRA)', 'ADAIR John (NIR)', 'FINNEY Jim (ENG)',
       'SBARDELLA Antonio (ITA)', 'LORAUX Vital (BEL)',
       'TAYLOR John (ENG)', 'VAN RAVENS Laurens (NED)',
       'BARRETO RUIZ Ramon (URU)', 'RADULESCU Andrei (ROU)',
       'GLOECKNER Rudolf (GDR)', 'DE LEO Diego (MEX)',
       'SCHEURER Ruedi (SUI)', 'TAREKEGN Seyoum (ETH)',
       'ORTIZ DE MENDIBIL Jose Maria (ESP)', 'KLEIN Abraham (ISR)',
       'LANDAUER Henry (USA)', 'AGUILAR ELIZALDE Abel (MEX)',
       'MARSCHALL Ferdinand (AUT)', 'HORMAZABAL DIAZ Rafael (CHI)',
       'DE MORAES Ayrton Vieira (BRA)', 'SALDANHA RIBEIRO Antonio (POR)',
       'MACHIN Roger (FRA)', 'COEREZZA Norberto Angel (ARG)',
       'BABACAN Dogan (TUR)', 'NDIAYE Youssou (SEN)',
       'SCHULENBURG Gerhard (GER)', 'PALOTAI Karoly (HUN)',
       'PEREZ NUNEZ Edison A. (PER)', 'LLOBREGAT Vicente (VEN)',
       'THOMAS Clive (WAL)', 'KAMEL Mahmoud (EGY)',
       'VAN GEMERT Arie (NED)', 'ANGONESE Aurelio (ITA)',
       'DELGADO Omar (COL)', 'WINSEMANN Werner (CAN)',
       'SUPPIAH George (SIN)', 'KAZAKOV Pavel (URS)',
       'GONZALEZ ARCHUNDIA Alfonso (MEX)', 'NAMDAR Jafar (IRN)',
       'RAINEA Nicolae (ROU)', 'BOSKOVIC Tony (AUS)',
       'SANCHEZ IBANEZ Pablo (ESP)', 'LINEMAYR Erich (AUT)',
       'WEYLAND Hans Joachim (FRG)', 'PESTARINO Luis (ARG)',
       'GORDON John (SCO)', 'GARRIDO Antonio (POR)', 'ERIKSSON Ulf (SWE)',
       'MARTINEZ Angel (ESP)', 'BOUZO Farouk (SYR)', 'DUBACH Jean (SUI)',
       'GONELLA Sergio (ITA)', 'CORVER Charles (NED)',
       'PROKOP Adolf (GDR)', 'COELHO Arnaldo (BRA)',
       'OROZCO GUERRERO Cesar (PER)', 'WURTZ Robert (FRA)',
       'BIWERSI Ferdinand (GER)', 'JARGUZ Alojzy (POL)',
       'MAKSIMOVIC Dusan (SCG)', 'PARTRIDGE Pat (ENG)',
       'RION Francis (BEL)', 'SILVAGNO CAVANNA Juan (CHI)',
       'CHRISTOV Vojtech (TCH)', 'VAUTROT Michel (FRA)',
       'LAMO CASTILLO Augusto (ESP)', 'WOEHRER Franz (AUT)',
       'AL DOY Ebrahim (BHR)', 'SOCHA David (USA)',
       'LABO REVOREDO Enrique (PER)', 'ITHURRALDE Arturo Andres (ARG)',
       'CARDELLINO DE SAN VICENTE Juan (URU)', 'DWOMOH Benjamin (GHA)',
       'FREDRIKSSON Erik (SWE)', 'ESCHWEILER Walter (GER)',
       'LACARNE Belaid (ALG)', 'SILES Jesus Paulino (CRC)',
       'PONNET Alexis (BEL)', 'MOFFATT Malcolm (NIR)',
       'EL GHOUL Yusef Mohamed (LBY)', 'GALLER Bruno (SUI)',
       'LUND-SORENSEN Henning (DEN)', 'STUPAR Miroslav (URS)',
       'CHAN Thomson Tam Sun (HKG)', 'RUBIO VAZQUEZ Mario (MEX)',
       'WHITE Clive (ENG)', 'DOTCHEV Bogdan (BUL)',
       'BARRANCOS Luis (BOL)', 'MATOVINOVIC Damir (CRO)',
       'MENDEZ MOLINA Romulo (GUA)', 'CASARIN Paolo (ITA)',
       'CASTRO Gaston (CHI)', 'VALENTINE Robert (SCO)',
       'ARISTIZABAL MURCIA Gilberto (COL)', 'ORTIZ Hector (PAR)',
       'SILVA ARCE Hernan (CHI)', 'BAMBRIDGE Christopher (AUS)',
       'AGNOLIN Luigi (ITA)', 'SANCHEZ ARMINIO Victoriano (ESP)',
       'MARTINEZ BAZAN Jose Luis (URU)', 'BUTENKO Valeri (RUS)',
       'ESPOSITO Carlos (ARG)', 'ROTH Volker (GER)',
       'PICON-ACKONG Edwin (MRI)', 'NEMETH Lajos (HUN)',
       'KEIZER Jan (NED)', 'ARPPI FILHO Romualdo (BRA)',
       'AL SHANAR Fallaj Khuzam (KSA)', 'AL SHARIF Jamal (SYR)',
       'GONZALEZ ROA Gabriel (PAR)', 'BRUMMEIER Horst (AUT)',
       'COURTNEY George (ENG)', 'BENNACEUR Ali (TUN)',
       'DIAZ PALACIO Jesus (COL)', 'MARQUEZ RAMIREZ Antonio (MEX)',
       'IGNA Ioan (ROU)', 'SILVA VALENTE Carlos Alberto (POR)',
       'TRAORE Idrissa (MLI)', 'ULLOA MORERA Berny (CRC)',
       'PETROVIC Zoran (SRB)', 'SNODDY Alan (NIR)', 'DAINA Andre (SUI)',
       'KIRSCHEN Siegfried (GER)', 'TAKADA Shizuo (JPN)',
       'QUINIOU Joel (FRA)', 'RAMIZ WRIGHT Jose (BRA)',
       'ROETHLISBERGER Kurt (SUI)', 'LANESE Tullio (ITA)',
       'MIKKELSEN Peter (DEN)', 'LOUSTAU Juan (ARG)',
       'SCHMIDHUBER Aron (GER)', 'MAURO Vincent (USA)',
       'SORIANO ALADREN Emilio (ESP)', 'KOHL Helmut (AUT)',
       'CODESAL MENDEZ Edgardo (MEX)', 'SMITH George (SCO)',
       'SPIRIN Alexey (RUS)', 'JOUINI Neji (TUN)', 'MACIEL Carlos (PAR)',
       'VAN LANGENHOVE Marcel (BEL)', 'JACOME GUERRERO Elias V. (ECU)',
       'BRIZIO CARTER Arturo (MEX)', 'LAMOLINA Francisco Oscar (ARG)',
       'VAN DER ENDE Mario (NED)', 'TORRES CADENA Jose Joaquin (COL)',
       'PUHL Sandor (HUN)', 'TEJADA NORIEGA Alberto (PER)',
       'DIAZ VEGA Manuel (ESP)', 'LIM KEE CHONG An Yan (MRI)',
       'ANGELES Arturo (USA)', 'BADILLA Rodrigo (CRC)',
       'FILIPPI Ernesto (URU)', 'BALDAS Fabio (ITA)',
       'KRUG Hellmut (GER)', 'MOTTRAM Leslie (SCO)',
       'MARSIGLIA Renato (BRA)', 'DON Philip (ENG)', 'KARLSSON Bo (SWE)',
       'BUJSAIM Ali (UAE)', 'PAIRETTO Pierluigi (ITA)',
       'GARCIA ARANDA Jose Maria (ESP)', 'ANPRASERT Pirom (THA)',
       'BOUCHARDEAU Lucien (NIG)', 'GONZALEZ CHAVEZ Epifanio (PAR)',
       'ALZEID Abdulrahman (KSA)', 'CASTRILLI Javier (ARG)',
       'REZENDE Marcio (BRA)', 'BAHARMAST Esse (USA)',
       'BENKO Gunter (AUT)', 'COLLINA Pierluigi (ITA)',
       'MELO PEREIRA Vitor (POR)', 'OKADA Masayoshi (JPN)',
       'BELQOLA Said (MAR)', 'VAGNER Laszlo (HUN)',
       'LEVNIKOV Nikolai (RUS)', 'EL GHANDOUR Gamal (EGY)',
       'LENNIE Edward (AUS)', 'TORO RENDON John (COL)',
       'SANCHEZ YANTEN Mario (CHI)', 'McLEOD Ian (RSA)',
       'RAMDHAN Ramesh (TRI)', 'DALLAS Hugh (SCO)',
       'WOJCIK Ryszard (POL)', 'NIELSEN Kim Milton (DEN)',
       'PEDERSEN Rune (NOR)', 'MEIER Urs (SUI)', 'HEYNEMANN Bernd (GER)',
       'BATTA Marc (FRA)', 'DURKIN Paul (ENG)', 'MANE Saad (KUW)',
       'KAMIKAWA Toru (JPN)', 'AQUINO Ubaldo (PAR)',
       'VEISSIERE Gilles (FRA)', 'MICHEL Lubos (SVK)',
       'SIMON Carlos (BRA)', 'GUEZZAZ Mohammed (MAR)',
       'KIM Young Joo (KOR)', 'HALL Brian (USA)', 'JUN Lu (CHN)',
       'VASSARAS Kyros (GRE)', 'MATTUS William (CRC)', 'RUIZ Oscar (COL)',
       'PRENDERGAST Peter (JAM)', 'MORENO Byron (ECU)',
       'BATRES Carlos (GUA)', 'HAUGE Terje (NOR)',
       'RAMOS RIZO Felipe (MEX)', 'ORTUBE Rene (BOL)',
       'SANCHEZ Angel (ARG)', 'FRISK Anders (SWE)', 'POLL Graham (ENG)',
       'CODJIA Coffi (BEN)', 'MERK Markus (GER)', 'DAAMI Mourad (TUN)',
       'SHIELD Mark (AUS)', 'WEGEREEF Jan (NED)', 'NDOYE Falla (SEN)',
       'LOPEZ NIETO Antonio (ESP)', 'LU Jun (CHN)',
       'ELIZONDO Horacio (ARG)', 'RODRIGUEZ Marco (MEX)',
       'MAIDIN Shamsul (SIN)', 'DE BLEECKERE Frank (BEL)',
       'ROSETTI Roberto (ITA)', 'LARRIONDA Jorge (URU)',
       'ABD EL FATAH Essam (EGY)', 'AMARILLA Carlos (PAR)',
       'IVANOV Valentin (RUS)', 'ARCHUNDIA Benito (MEX)',
       'BUSACCA Massimo (SUI)', 'MEDINA CANTALEJO Luis (ESP)',
       'POULAT Eric (FRA)', 'Ravshan IRMATOV (UZB)',
       'NISHIMURA Yuichi (JPN)', 'HESTER Michael (NZL)',
       'Wolfgang STARK (GER)', 'BALDASSI Hector (ARG)',
       'St�phane LANNOY (FRA)', 'Oleg�rio BENQUEREN�A (POR)',
       'DAMON Jerome (RSA)', 'KASSAI Viktor (HUN)', 'MAILLET Eddy (SEY)',
       'WEBB Howard (ENG)', 'AL GHAMDI Khalil (KSA)',
       'Alberto UNDIANO MALLENCO (ESP)', 'Koman COULIBALY (MLI)',
       'POZO Pablo (CHI)', 'ROLDAN Wilmar (COL)', 'Nicola RIZZOLI (ITA)',
       'Noumandiez DOUE (CIV)', 'GEIGER Mark (USA)', 'BRYCH Felix (GER)',
       'Bj�rn KUIPERS (NED)', 'OSSES Enrique (CHI)', 'RICCI Sandro (BRA)',
       'AGUILAR Joel (SLV)', 'MAZIC Milorad (SRB)', 'VERA Carlos (ECU)',
       'ERIKSSON Jonas (SWE)', 'C�neyt �AKIR (TUR)',
       'PITANA Nestor (ARG)', 'HAIMOUDI Djamel (ALG)',
       'PROENCA Pedro (POR)', 'Carlos VELASCO CARBALLO (ESP)',
       'Ben WILLIAMS (AUS)', "Peter O'LEARY (NZL)",
       'SHUKRALLA Nawaf (BHR)', 'Bakary GASSAMA (GAM)'], dtype=object)

In [26]:
df['referee'] = df['referee'].str.extract(r"\((.*?)\)", expand=False)

In [27]:
df['assistant_1'] = df['assistant_1'].str.extract(r"\((.*?)\)", expand=False)

In [28]:
df['assistant_2'] = df['assistant_2'].str.extract(r"\((.*?)\)", expand=False)

In [29]:
df.head()

,year,date,stage,stadium,city,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,attendance,half-time_home_goals,half-time_away_goals,referee,assistant_1,assistant_2,roundid,matchid,home_team_initials,away_team_initials
0,1930,13/07/1930,Group A,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,URU,BEL,BRA,201.0,1096.0,FRA,MEX
1,1930,13/07/1930,Group D,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,ARG,URU,CHI,201.0,1090.0,USA,BEL
2,1930,14/07/1930,Group B,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,URU,URU,FRA,201.0,1093.0,YUG,BRA
3,1930,14/07/1930,Group C,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,CHI,BEL,URU,201.0,1098.0,ROU,PER
4,1930,15/07/1930,Group A,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,BRA,BOL,ROU,201.0,1085.0,ARG,FRA

### Fixing country names:

We'll have to clean a few of the names in certain columns before using them later.

In [30]:
home_countries = df['home_team_name'].unique()

home_countries.sort()

display(home_countries)

array(['Algeria', 'Angola', 'Argentina', 'Australia', 'Austria',
       'Belgium', 'Bolivia', 'Brazil', 'Bulgaria', 'Cameroon', 'Canada',
       'Chile', 'China PR', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba',
       'Czech Republic', 'Czechoslovakia', "C�te d'Ivoire", 'Denmark',
       'Ecuador', 'England', 'France', 'German DR', 'Germany',
       'Germany FR', 'Ghana', 'Greece', 'Haiti', 'Honduras', 'Hungary',
       'IR Iran', 'Iran', 'Iraq', 'Italy', 'Jamaica', 'Japan',
       'Korea DPR', 'Korea Republic', 'Mexico', 'Morocco', 'Netherlands',
       'New Zealand', 'Nigeria', 'Northern Ireland', 'Norway', 'Paraguay',
       'Peru', 'Poland', 'Portugal', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Senegal', 'Serbia', 'Slovakia', 'Slovenia',
       'South Africa', 'Soviet Union', 'Spain', 'Sweden', 'Switzerland',
       'Togo', 'Tunisia', 'Turkey', 'USA', 'Ukraine', 'Uruguay', 'Wales',
       'Yugoslavia', 'Zaire', 'rn">Bosnia and Herzegovina',
       'rn">Republic of Ireland', 'rn">Serbia and Montenegro',
       'rn">Trinidad and Tobago', 'rn">United Arab Emirates'],
      dtype=object)

In [31]:
away_countries = df['away_team_name'].unique()

away_countries.sort()

display(away_countries)

array(['Algeria', 'Angola', 'Argentina', 'Australia', 'Austria',
       'Belgium', 'Bolivia', 'Brazil', 'Bulgaria', 'Cameroon', 'Canada',
       'Chile', 'China PR', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba',
       'Czech Republic', 'Czechoslovakia', "C�te d'Ivoire", 'Denmark',
       'Dutch East Indies', 'Ecuador', 'Egypt', 'El Salvador', 'England',
       'France', 'German DR', 'Germany', 'Germany FR', 'Ghana', 'Greece',
       'Haiti', 'Honduras', 'Hungary', 'IR Iran', 'Iran', 'Iraq',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Korea DPR',
       'Korea Republic', 'Kuwait', 'Mexico', 'Morocco', 'Netherlands',
       'New Zealand', 'Nigeria', 'Northern Ireland', 'Norway', 'Paraguay',
       'Peru', 'Poland', 'Portugal', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Senegal', 'Serbia', 'Slovakia', 'Slovenia',
       'South Africa', 'Soviet Union', 'Spain', 'Sweden', 'Switzerland',
       'Togo', 'Tunisia', 'Turkey', 'USA', 'Ukraine', 'Uruguay', 'Wales',
       'Yugoslavia', 'Zaire', 'rn">Bosnia and Herzegovina',
       'rn">Republic of Ireland', 'rn">Serbia and Montenegro',
       'rn">Trinidad and Tobago', 'rn">United Arab Emirates'],
      dtype=object)

Need to fix the names of the following countries in the team names columns: 
 - C�te d'Ivoire.
 - Turn 'IR Iran' into Iran.
 - Remove the (rn">) from: Republic of Ireland, Serbia and Montenegro, Trinidad and Tobago, United Arab Emirates.

Using a lambda function to fix the names of Ivory Coast and Iran for both home_team_name and away_team_name:

In [32]:
df['home_team_name'] = df['home_team_name'].map(lambda x: x.replace('C�te', 'Côte'))

df['home_team_name'].unique()

array(['France', 'USA', 'Yugoslavia', 'Romania', 'Argentina', 'Chile',
       'Uruguay', 'Brazil', 'Paraguay', 'Austria', 'Hungary',
       'Switzerland', 'Sweden', 'Germany', 'Spain', 'Italy',
       'Czechoslovakia', 'Cuba', 'England', 'Germany FR', 'Turkey',
       'Soviet Union', 'Northern Ireland', 'Mexico', 'Wales', 'Portugal',
       'Korea DPR', 'Peru', 'Belgium', 'Bulgaria', 'German DR', 'Zaire',
       'Poland', 'Australia', 'Scotland', 'Netherlands', 'Haiti',
       'Tunisia', 'Algeria', 'Honduras', 'Canada', 'Morocco',
       'Korea Republic', 'Iraq', 'Denmark', 'rn">United Arab Emirates',
       'Costa Rica', 'Cameroon', 'rn">Republic of Ireland', 'Colombia',
       'Norway', 'Nigeria', 'Saudi Arabia', 'Bolivia', 'Russia', 'Greece',
       'Jamaica', 'South Africa', 'Japan', 'Croatia', 'China PR',
       'Senegal', 'Slovenia', 'Ecuador', 'rn">Trinidad and Tobago',
       'rn">Serbia and Montenegro', 'Angola', 'Czech Republic', 'Togo',
       'Iran', "Côte d'Ivoire", 'Ghana', 'Ukraine', 'Serbia',
       'New Zealand', 'Slovakia', 'IR Iran', 'rn">Bosnia and Herzegovina'],
      dtype=object)

In [33]:
df['away_team_name'] = df['away_team_name'].map(lambda x: x.replace('C�te', 'Côte'))

df['away_team_name'].unique()

array(['Mexico', 'Belgium', 'Brazil', 'Peru', 'France', 'Bolivia',
       'Paraguay', 'Romania', 'Chile', 'USA', 'Yugoslavia', 'Argentina',
       'Egypt', 'Netherlands', 'Switzerland', 'Sweden', 'Spain',
       'Hungary', 'Austria', 'Germany', 'Czechoslovakia',
       'Dutch East Indies', 'Norway', 'Poland', 'Cuba', 'Italy',
       'England', 'Scotland', 'Turkey', 'Korea Republic', 'Germany FR',
       'Uruguay', 'Wales', 'Northern Ireland', 'Soviet Union', 'Colombia',
       'Bulgaria', 'Korea DPR', 'Portugal', 'Israel', 'Morocco',
       'El Salvador', 'Australia', 'Haiti', 'German DR', 'Zaire',
       'IR Iran', 'Tunisia', 'Iran', 'Cameroon', 'New Zealand', 'Algeria',
       'Honduras', 'Kuwait', 'Iraq', 'Denmark', 'Canada',
       'rn">Republic of Ireland', 'rn">United Arab Emirates',
       'Costa Rica', 'Saudi Arabia', 'Russia', 'Greece', 'Nigeria',
       'South Africa', 'Japan', 'Croatia', 'Jamaica', 'Senegal',
       'Slovenia', 'Ecuador', 'China PR', "Côte d'Ivoire",
       'Czech Republic', 'Ghana', 'Togo', 'Ukraine',
       'rn">Trinidad and Tobago', 'rn">Serbia and Montenegro', 'Angola',
       'Slovakia', 'Serbia', 'rn">Bosnia and Herzegovina'], dtype=object)

In [34]:
df['home_team_name'] = df['home_team_name'].map(lambda x: x.replace('IR Iran', 'Iran'))

df['home_team_name'].unique()

array(['France', 'USA', 'Yugoslavia', 'Romania', 'Argentina', 'Chile',
       'Uruguay', 'Brazil', 'Paraguay', 'Austria', 'Hungary',
       'Switzerland', 'Sweden', 'Germany', 'Spain', 'Italy',
       'Czechoslovakia', 'Cuba', 'England', 'Germany FR', 'Turkey',
       'Soviet Union', 'Northern Ireland', 'Mexico', 'Wales', 'Portugal',
       'Korea DPR', 'Peru', 'Belgium', 'Bulgaria', 'German DR', 'Zaire',
       'Poland', 'Australia', 'Scotland', 'Netherlands', 'Haiti',
       'Tunisia', 'Algeria', 'Honduras', 'Canada', 'Morocco',
       'Korea Republic', 'Iraq', 'Denmark', 'rn">United Arab Emirates',
       'Costa Rica', 'Cameroon', 'rn">Republic of Ireland', 'Colombia',
       'Norway', 'Nigeria', 'Saudi Arabia', 'Bolivia', 'Russia', 'Greece',
       'Jamaica', 'South Africa', 'Japan', 'Croatia', 'China PR',
       'Senegal', 'Slovenia', 'Ecuador', 'rn">Trinidad and Tobago',
       'rn">Serbia and Montenegro', 'Angola', 'Czech Republic', 'Togo',
       'Iran', "Côte d'Ivoire", 'Ghana', 'Ukraine', 'Serbia',
       'New Zealand', 'Slovakia', 'rn">Bosnia and Herzegovina'],
      dtype=object)

In [35]:
df['away_team_name'] = df['away_team_name'].map(lambda x: x.replace('IR Iran', 'Iran'))

df['away_team_name'].unique()

array(['Mexico', 'Belgium', 'Brazil', 'Peru', 'France', 'Bolivia',
       'Paraguay', 'Romania', 'Chile', 'USA', 'Yugoslavia', 'Argentina',
       'Egypt', 'Netherlands', 'Switzerland', 'Sweden', 'Spain',
       'Hungary', 'Austria', 'Germany', 'Czechoslovakia',
       'Dutch East Indies', 'Norway', 'Poland', 'Cuba', 'Italy',
       'England', 'Scotland', 'Turkey', 'Korea Republic', 'Germany FR',
       'Uruguay', 'Wales', 'Northern Ireland', 'Soviet Union', 'Colombia',
       'Bulgaria', 'Korea DPR', 'Portugal', 'Israel', 'Morocco',
       'El Salvador', 'Australia', 'Haiti', 'German DR', 'Zaire', 'Iran',
       'Tunisia', 'Cameroon', 'New Zealand', 'Algeria', 'Honduras',
       'Kuwait', 'Iraq', 'Denmark', 'Canada', 'rn">Republic of Ireland',
       'rn">United Arab Emirates', 'Costa Rica', 'Saudi Arabia', 'Russia',
       'Greece', 'Nigeria', 'South Africa', 'Japan', 'Croatia', 'Jamaica',
       'Senegal', 'Slovenia', 'Ecuador', 'China PR', "Côte d'Ivoire",
       'Czech Republic', 'Ghana', 'Togo', 'Ukraine',
       'rn">Trinidad and Tobago', 'rn">Serbia and Montenegro', 'Angola',
       'Slovakia', 'Serbia', 'rn">Bosnia and Herzegovina'], dtype=object)

Now we'll do the same to remove the 'rn">' from Republic of Ireland, Serbia and Montenegro, Trinidad and Tobago, United Arab Emirates.

In [36]:
df['home_team_name'] = df['home_team_name'].map(lambda x: x.lstrip('rn">'))

df['home_team_name'].unique()

array(['France', 'USA', 'Yugoslavia', 'Romania', 'Argentina', 'Chile',
       'Uruguay', 'Brazil', 'Paraguay', 'Austria', 'Hungary',
       'Switzerland', 'Sweden', 'Germany', 'Spain', 'Italy',
       'Czechoslovakia', 'Cuba', 'England', 'Germany FR', 'Turkey',
       'Soviet Union', 'Northern Ireland', 'Mexico', 'Wales', 'Portugal',
       'Korea DPR', 'Peru', 'Belgium', 'Bulgaria', 'German DR', 'Zaire',
       'Poland', 'Australia', 'Scotland', 'Netherlands', 'Haiti',
       'Tunisia', 'Algeria', 'Honduras', 'Canada', 'Morocco',
       'Korea Republic', 'Iraq', 'Denmark', 'United Arab Emirates',
       'Costa Rica', 'Cameroon', 'Republic of Ireland', 'Colombia',
       'Norway', 'Nigeria', 'Saudi Arabia', 'Bolivia', 'Russia', 'Greece',
       'Jamaica', 'South Africa', 'Japan', 'Croatia', 'China PR',
       'Senegal', 'Slovenia', 'Ecuador', 'Trinidad and Tobago',
       'Serbia and Montenegro', 'Angola', 'Czech Republic', 'Togo',
       'Iran', "Côte d'Ivoire", 'Ghana', 'Ukraine', 'Serbia',
       'New Zealand', 'Slovakia', 'Bosnia and Herzegovina'], dtype=object)

In [37]:
df['away_team_name'] = df['away_team_name'].map(lambda x: x.lstrip('rn">'))

df['away_team_name'].unique()

array(['Mexico', 'Belgium', 'Brazil', 'Peru', 'France', 'Bolivia',
       'Paraguay', 'Romania', 'Chile', 'USA', 'Yugoslavia', 'Argentina',
       'Egypt', 'Netherlands', 'Switzerland', 'Sweden', 'Spain',
       'Hungary', 'Austria', 'Germany', 'Czechoslovakia',
       'Dutch East Indies', 'Norway', 'Poland', 'Cuba', 'Italy',
       'England', 'Scotland', 'Turkey', 'Korea Republic', 'Germany FR',
       'Uruguay', 'Wales', 'Northern Ireland', 'Soviet Union', 'Colombia',
       'Bulgaria', 'Korea DPR', 'Portugal', 'Israel', 'Morocco',
       'El Salvador', 'Australia', 'Haiti', 'German DR', 'Zaire', 'Iran',
       'Tunisia', 'Cameroon', 'New Zealand', 'Algeria', 'Honduras',
       'Kuwait', 'Iraq', 'Denmark', 'Canada', 'Republic of Ireland',
       'United Arab Emirates', 'Costa Rica', 'Saudi Arabia', 'Russia',
       'Greece', 'Nigeria', 'South Africa', 'Japan', 'Croatia', 'Jamaica',
       'Senegal', 'Slovenia', 'Ecuador', 'China PR', "Côte d'Ivoire",
       'Czech Republic', 'Ghana', 'Togo', 'Ukraine',
       'Trinidad and Tobago', 'Serbia and Montenegro', 'Angola',
       'Slovakia', 'Serbia', 'Bosnia and Herzegovina'], dtype=object)

### Dropping unnecessary and/or redudant columns:

Since we already get the country names from home_team_name and away_team_name we won't need to know their initials, so we'll be dropping home_team_initials and away_team_initials.

The columns roundid and matchid display information that's not relevant so we'll get rid of these as well.

In [38]:
df = df.drop(['roundid', 'matchid', 'home_team_initials', 'away_team_initials'], axis=1)

df.head()

,year,date,stage,stadium,city,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,attendance,half-time_home_goals,half-time_away_goals,referee,assistant_1,assistant_2
0,1930,13/07/1930,Group A,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,URU,BEL,BRA
1,1930,13/07/1930,Group D,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,ARG,URU,CHI
2,1930,14/07/1930,Group B,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,URU,URU,FRA
3,1930,14/07/1930,Group C,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,CHI,BEL,URU
4,1930,15/07/1930,Group A,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,BRA,BOL,ROU

### Host country:

Next we'll be using the column years to create a new column with the host of the World Cup during that year and then we'll drop the 'year' column.

In [39]:
df['year'].unique()

array([1930, 1934, 1938, 1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978,
       1982, 1986, 1990, 1994, 1998, 2002, 2006, 2010, 2014])

In [40]:
def host_country(x):
    
    if x == 1930:
        return 'Uruguay'
    elif x == 1934:
        return 'Italy'
    elif x == 1938:
        return 'France'
    elif x == 1950:
        return 'Brasil'
    elif x == 1954:
        return 'Switzerland'
    elif x == 1958:
        return 'Sweden'
    elif x == 1962:
        return 'Chile'
    elif x == 1966:
        return 'England'
    elif x == 1970:
        return 'Mexico'
    elif x == 1974:
        return 'West Germany'
    elif x == 1978: 
        return 'Argentina'
    elif x == 1982:
        return 'Spain'
    elif x == 1986:
        return 'Mexico'
    elif x == 1990:
        return 'Italy'
    elif x == 1994:
        return 'USA'
    elif x == 1998:
        return 'France'
    elif x == 2002:
        return 'South Korea & Japan'
    elif x == 2006:
        return 'Germany'
    elif x == 2010: 
        return 'South Africa'
    elif x == 2014:
        return 'Brasil'

In [41]:
df['host_country'] = list(map(host_country,df['year']))

In [42]:
df = df.drop(['year'], axis=1)

df.tail()

,date,stage,stadium,city,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,attendance,half-time_home_goals,half-time_away_goals,referee,assistant_1,assistant_2,host_country
847,05/07/2014,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),51179,0,0,UZB,UZB,KGZ,Brasil
848,08/07/2014,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,58141,0,5,MEX,MEX,MEX,Brasil
849,09/07/2014,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267,0,0,TUR,TUR,TUR,Brasil
850,12/07/2014,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034,0,2,ALG,MAR,ALG,Brasil
851,13/07/2014,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738,0,0,ITA,ITA,ITA,Brasil

### Finding out the winner at half time:

For this we'll create a new column with the 'winner at half time' through the following function:
 - If the home team has more goals than the away team at half time, return the home team name.
 - If the home team has less goals than the away team at half time, return the away team name.
 - For every other result (home team has the same goals than the away team at half time) return 'Tie'.

In [43]:
def half_time(row):
    
    if row['half-time_home_goals'] > row['half-time_away_goals']:
        return row["home_team_name"]
    elif row['half-time_home_goals'] < row['half-time_away_goals']:
        return row["away_team_name"]
    else: 
        return 'Tie'

In [44]:
df['half-time_winner'] = df.apply(half_time, axis=1)

In [45]:
df.head()

,date,stage,stadium,city,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,attendance,half-time_home_goals,half-time_away_goals,referee,assistant_1,assistant_2,host_country,half-time_winner
0,13/07/1930,Group A,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,URU,BEL,BRA,Uruguay,France
1,13/07/1930,Group D,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,ARG,URU,CHI,Uruguay,USA
2,14/07/1930,Group B,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,URU,URU,FRA,Uruguay,Yugoslavia
3,14/07/1930,Group C,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,CHI,BEL,URU,Uruguay,Romania
4,15/07/1930,Group A,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,BRA,BOL,ROU,Uruguay,Tie

### Finding out the winner at full time (before the penalty shootout):

We repeat the same process as before but using the home/away_team_goals. These columns show the goals during the whole game, including aggregate time but not including penalty shootouts.

In [46]:
def full_time(row):
    
    if row['home_team_goals'] > row['away_team_goals']:
        return row["home_team_name"]
    elif row['home_team_goals'] < row['away_team_goals']:
        return row["away_team_name"]
    else: 
        return 'Penalties'

In [47]:
df['full-time_winner'] = df.apply(full_time, axis=1)

In [48]:
df.tail(10)

,date,stage,stadium,city,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,attendance,half-time_home_goals,half-time_away_goals,referee,assistant_1,assistant_2,host_country,half-time_winner,full-time_winner
842,01/07/2014,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1,0,Switzerland,Argentina win after extra time,63255,0,0,SWE,SWE,SWE,Brasil,Tie,Argentina
843,01/07/2014,Round of 16,Arena Fonte Nova,Salvador,Belgium,2,1,USA,Belgium win after extra time,51227,0,0,ALG,MAR,ALG,Brasil,Tie,Belgium
844,04/07/2014,Quarter-finals,Estadio do Maracana,Rio De Janeiro,France,0,1,Germany,,74240,0,1,ARG,ARG,ARG,Brasil,Germany,Germany
845,04/07/2014,Quarter-finals,Estadio Castelao,Fortaleza,Brazil,2,1,Colombia,,60342,1,0,ESP,ESP,ESP,Brasil,Brazil,Brazil
846,05/07/2014,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1,0,Belgium,,68551,1,0,ITA,ITA,ITA,Brasil,Argentina,Argentina
847,05/07/2014,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),51179,0,0,UZB,UZB,KGZ,Brasil,Tie,Penalties
848,08/07/2014,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,58141,0,5,MEX,MEX,MEX,Brasil,Germany,Germany
849,09/07/2014,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267,0,0,TUR,TUR,TUR,Brasil,Tie,Penalties
850,12/07/2014,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034,0,2,ALG,MAR,ALG,Brasil,Netherlands,Netherlands
851,13/07/2014,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738,0,0,ITA,ITA,ITA,Brasil,Tie,Germany

### Reorganizing the columns:

We'll be swapping around the order of the columns so the data is easier to read.

In [49]:
df = df[['date', 'stage', "host_country", 'city', 'stadium', 'attendance', 'home_team_name',
        'home_team_goals', 'away_team_goals', 'away_team_name', 'win_conditions', 
         'half-time_home_goals', 'half-time_away_goals', 'half-time_winner',
         'full-time_winner', 'referee', 'assistant_1', 'assistant_2']]
df.tail()

,date,stage,host_country,city,stadium,attendance,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,half-time_home_goals,half-time_away_goals,half-time_winner,full-time_winner,referee,assistant_1,assistant_2
847,05/07/2014,Quarter-finals,Brasil,Salvador,Arena Fonte Nova,51179,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),0,0,Tie,Penalties,UZB,UZB,KGZ
848,08/07/2014,Semi-finals,Brasil,Belo Horizonte,Estadio Mineirao,58141,Brazil,1,7,Germany,,0,5,Germany,Germany,MEX,MEX,MEX
849,09/07/2014,Semi-finals,Brasil,Sao Paulo,Arena de Sao Paulo,63267,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),0,0,Tie,Penalties,TUR,TUR,TUR
850,12/07/2014,Play-off for third place,Brasil,Brasilia,Estadio Nacional,68034,Brazil,0,3,Netherlands,,0,2,Netherlands,Netherlands,ALG,MAR,ALG
851,13/07/2014,Final,Brasil,Rio De Janeiro,Estadio do Maracana,74738,Germany,1,0,Argentina,Germany win after extra time,0,0,Tie,Germany,ITA,ITA,ITA

### Statistical hypothesis testing:  games tied at half time and penalty shootouts.

Null hypothesis: Tied games at half-time and penalty shootouts are not related.

Alternative hypothesis: Tied games at half-time and penalty shootouts are rea.

In [50]:
winner_crosstab = df[(df['half-time_winner'] == 'Tie')|(df['full-time_winner'] == 'Penalties')]

In [51]:
data_crosstab = pd.crosstab(winner_crosstab['half-time_winner'], winner_crosstab['full-time_winner'], margins = False)
data_crosstab

full-time_winner,Algeria,Argentina,Australia,Austria,Belgium,Brazil,Bulgaria,Cameroon,Chile,Colombia,...,Slovenia,Soviet Union,Spain,Sweden,Switzerland,Turkey,USA,Ukraine,Uruguay,Yugoslavia
half-time_winner,,,,,,,,,,,,,,,,,,,,,
Austria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Belgium,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Brazil,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bulgaria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cameroon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Chile,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Czechoslovakia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Denmark,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
England,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
France,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Germany,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Honduras,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Hungary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Italy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mexico,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Netherlands,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Northern Ireland,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Paraguay,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Portugal,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Russia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Scotland,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Senegal,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Slovenia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Soviet Union,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Spain,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Sweden,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tie,1,15,1,5,8,28,2,4,5,4,...,1,7,10,9,3,1,1,1,6,8
Tunisia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
USA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Uruguay,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Wales,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Yugoslavia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [52]:
st.chi2_contingency(data_crosstab)

(77.59088442756374,
 1.0,
 1519,
 array([[0.00227273, 0.03409091, 0.00227273, ..., 0.00227273, 0.01363636,
         0.01818182],
        [0.00681818, 0.10227273, 0.00681818, ..., 0.00681818, 0.04090909,
         0.05454545],
        [0.00227273, 0.03409091, 0.00227273, ..., 0.00227273, 0.01363636,
         0.01818182],
        ...,
        [0.00227273, 0.03409091, 0.00227273, ..., 0.00227273, 0.01363636,
         0.01818182],
        [0.00227273, 0.03409091, 0.00227273, ..., 0.00227273, 0.01363636,
         0.01818182],
        [0.00681818, 0.10227273, 0.00681818, ..., 0.00681818, 0.04090909,
         0.05454545]]))

In [53]:
st.chi2.ppf(0.95,df=1519)

1610.7838425265738

We accept the null hypothesis, there's no relation between tied games at half time and pentaly shootouts.

### Statistical hypothesis testing: how likely is for the host country to reach the final?

Null hypothesis: home team name and final stage are not related, when home team name is equal to host country.

Alternative hypothesis: host country and final are related, when home team name is equal to host country.

In [54]:
host_crosstab = df[(df['stage'] == 'Final')|(df['home_team_name'] == df['host_country'] )]

In [55]:
data_host_crosstab = pd.crosstab(host_crosstab['stage'], host_crosstab['home_team_name'], margins = False)

In [56]:
st.chi2_contingency(data_host_crosstab)

(300.39617031997983,
 4.5254773600482714e-08,
 180,
 array([[1.75  , 1.25  , 1.    , 1.5   , 1.5   , 2.25  , 0.5   , 3.75  ,
         1.25  , 0.5   , 0.5   , 0.75  , 1.25  , 0.5   , 0.75  , 1.    ],
        [0.0875, 0.0625, 0.05  , 0.075 , 0.075 , 0.1125, 0.025 , 0.1875,
         0.0625, 0.025 , 0.025 , 0.0375, 0.0625, 0.025 , 0.0375, 0.05  ],
        [0.175 , 0.125 , 0.1   , 0.15  , 0.15  , 0.225 , 0.05  , 0.375 ,
         0.125 , 0.05  , 0.05  , 0.075 , 0.125 , 0.05  , 0.075 , 0.1   ],
        [1.575 , 1.125 , 0.9   , 1.35  , 1.35  , 2.025 , 0.45  , 3.375 ,
         1.125 , 0.45  , 0.45  , 0.675 , 1.125 , 0.45  , 0.675 , 0.9   ],
        [0.6125, 0.4375, 0.35  , 0.525 , 0.525 , 0.7875, 0.175 , 1.3125,
         0.4375, 0.175 , 0.175 , 0.2625, 0.4375, 0.175 , 0.2625, 0.35  ],
        [0.7   , 0.5   , 0.4   , 0.6   , 0.6   , 0.9   , 0.2   , 1.5   ,
         0.5   , 0.2   , 0.2   , 0.3   , 0.5   , 0.2   , 0.3   , 0.4   ],
        [0.175 , 0.125 , 0.1   , 0.15  , 0.15  , 0.225 , 0.05  , 0.375 ,
         0.125 , 0.05  , 0.05  , 0.075 , 0.125 , 0.05  , 0.075 , 0.1   ],
        [0.175 , 0.125 , 0.1   , 0.15  , 0.15  , 0.225 , 0.05  , 0.375 ,
         0.125 , 0.05  , 0.05  , 0.075 , 0.125 , 0.05  , 0.075 , 0.1   ],
        [0.0875, 0.0625, 0.05  , 0.075 , 0.075 , 0.1125, 0.025 , 0.1875,
         0.0625, 0.025 , 0.025 , 0.0375, 0.0625, 0.025 , 0.0375, 0.05  ],
        [0.6125, 0.4375, 0.35  , 0.525 , 0.525 , 0.7875, 0.175 , 1.3125,
         0.4375, 0.175 , 0.175 , 0.2625, 0.4375, 0.175 , 0.2625, 0.35  ],
        [0.35  , 0.25  , 0.2   , 0.3   , 0.3   , 0.45  , 0.1   , 0.75  ,
         0.25  , 0.1   , 0.1   , 0.15  , 0.25  , 0.1   , 0.15  , 0.2   ],
        [0.6125, 0.4375, 0.35  , 0.525 , 0.525 , 0.7875, 0.175 , 1.3125,
         0.4375, 0.175 , 0.175 , 0.2625, 0.4375, 0.175 , 0.2625, 0.35  ],
        [0.0875, 0.0625, 0.05  , 0.075 , 0.075 , 0.1125, 0.025 , 0.1875,
         0.0625, 0.025 , 0.025 , 0.0375, 0.0625, 0.025 , 0.0375, 0.05  ]]))

In [57]:
st.chi2.ppf(0.95,df=180)

212.3039127469521

We reject the null hypothesis, the stage and the home team are not related.

In [58]:
df.to_csv('df_clean.csv')

In [63]:
df.iloc[60:851]

,date,stage,host_country,city,stadium,attendance,home_team_name,home_team_goals,away_team_goals,away_team_name,win_conditions,half-time_home_goals,half-time_away_goals,half-time_winner,full-time_winner,referee,assistant_1,assistant_2
60,29/06/1950,Group B,Brasil,Rio De Janeiro,Maracanã - Estádio Jornalista Mário Filho,19790,Spain,2,0,Chile,,2,0,Spain,Spain,BRA,URU,BOL
61,29/06/1950,Group C,Brasil,Curitiba,Durival de Brito,7903,Sweden,2,2,Paraguay,,2,1,Sweden,Penalties,SCO,YUG,USA
62,29/06/1950,Group B,Brasil,Belo Horizonte,Independencia,10151,USA,1,0,England,,1,0,USA,USA,ITA,FRA,ITA
63,01/07/1950,Group A,Brasil,Rio De Janeiro,Maracanã - Estádio Jornalista Mário Filho,142429,Brazil,2,0,Yugoslavia,,1,0,Brazil,Brazil,WAL,AUT,POR
64,02/07/1950,Group B,Brasil,Rio De Janeiro,Maracanã - Estádio Jornalista Mário Filho,74462,Spain,1,0,England,,0,0,Tie,Spain,ITA,SUI,ITA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,05/07/2014,Quarter-finals,Brasil,Salvador,Arena Fonte Nova,51179,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),0,0,Tie,Penalties,UZB,UZB,KGZ
848,08/07/2014,Semi-finals,Brasil,Belo Horizonte,Estadio Mineirao,58141,Brazil,1,7,Germany,,0,5,Germany,Germany,MEX,MEX,MEX
849,09/07/2014,Semi-finals,Brasil,Sao Paulo,Arena de Sao Paulo,63267,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),0,0,Tie,Penalties,TUR,TUR,TUR
850,12/07/2014,Play-off for third place,Brasil,Brasilia,Estadio Nacional,68034,Brazil,0,3,Netherlands,,0,2,Netherlands,Netherlands,ALG,MAR,ALG
851,13/07/2014,Final,Brasil,Rio De Janeiro,Estadio do Maracana,74738,Germany,1,0,Argentina,Germany win after extra time,0,0,Tie,Germany,ITA,ITA,ITA